=== Azcion/ZBP2/xml/track.dtd
<!ELEMENT track (id, name, explicit, popularity, preview_url, track_number, duration_ms, artists, album)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT explicit (#PCDATA)>
<!ELEMENT popularity (#PCDATA)>
<!ELEMENT preview_url (#PCDATA)>
<!ELEMENT track_number (#PCDATA)>
<!ELEMENT duration_ms (#PCDATA)>
<!ELEMENT artists (artist+)>
<!ELEMENT artist (id, name)>
<!ELEMENT album (name, release_date, release_date_precision, total_tracks, artists, image)>
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT release_date_precision (#PCDATA)>
<!ELEMENT total_tracks (#PCDATA)>
<!ELEMENT image (height, width, url)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== Azcion/ZBP2/xml/track-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="track.css"?>
<!DOCTYPE track SYSTEM "track.dtd">

<track
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="track.xsd">
  <id>4S7YHmlWwfwArgd8LfSPud</id>
  <name>L$D</name>
  <explicit>true</explicit>
  <popularity>77</popularity>
  <preview_url>https://p.scdn.co/mp3-preview/8b71919390097cca1e65c1787cc879556f1a571c?cid=774b29d4f13844c495f206cafdad9c86</preview_url>
  <track_number>4</track_number>
  <duration_ms>238306</duration_ms>
  <artists>
    <artist>
      <id>13ubrt8QOOCPljQ2FL1Kca</id>
      <name>A$AP Rocky</name>
    </artist>
  </artists>
  <album>
    <name>AT.LONG.LAST.A$AP</name>
    <release_date>2015-05-26</release_date>
    <release_date_precision>day</release_date_precision>
    <total_tracks>18</total_tracks>
    <artists>
      <artist>
        <id>13ubrt8QOOCPljQ2FL1Kca</id>
        <name>A$AP Rocky</name>
      </artist>
    </artists>
    <image>
      <height>640</height>
      <width>640</width>
      <url>https://i.scdn.co/image/ab67616d0000b27381a6a2cafab2e7a4066b5eec</url>
    </image>
  </album>
</track>

=== Azcion/ZBP2/xml/track-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="track.css"?>
<!DOCTYPE track SYSTEM "track.dtd">

<track
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="track.xsd">
  <id>3pXVWgkWybiGchdKGYDgdl</id>
  <name>Heat Waves (ft. iann dior)</name>
  <explicit>false</explicit>
  <popularity>63</popularity>
  <preview_url>https://p.scdn.co/mp3-preview/7d5595f2ce7fefa4d1bc43dcce7c3cd69d81fe6c?cid=774b29d4f13844c495f206cafdad9c86</preview_url>
  <track_number>1</track_number>
  <duration_ms>175301</duration_ms>
  <artists>
    <artist>
      <id>4yvcSjfu4PC0CYQyLy4wSq</id>
      <name>Glass Animals</name>
    </artist>
    <artist>
      <id>6ASri4ePR7RlsvIQgWPJpS</id>
      <name>iann dior</name>
    </artist>
  </artists>
  <album>
    <name>Faded Love</name>
    <release_date>2021-03-25</release_date>
    <release_date_precision>day</release_date_precision>
    <total_tracks>2</total_tracks>
    <artists>
      <artist>
        <id>4yvcSjfu4PC0CYQyLy4wSq</id>
        <name>Glass Animals</name>
      </artist>
    </artists>
    <image>
      <height>640</height>
      <width>640</width>
      <url>https://i.scdn.co/image/ab67616d0000b273617adf73c369292cb71457b7</url>
    </image>
  </album>
</track>

=== Azcion/ZBP2/xml/track-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="track.css"?>
<!DOCTYPE track SYSTEM "C:\Users\Zak\Documents\xml\xml\track.dtd">

<track
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="track.xsd">
  <id>0BJmDoQl8AwElUL7lMEuB8</id>
  <name>Faded Love</name>
  <explicit>false</explicit>
  <popularity>56</popularity>
  <preview_url>https://p.scdn.co/mp3-preview/5bbc377e4e0d05cd03010e4f005e82521668f6f9?cid=774b29d4f13844c495f206cafdad9c86</preview_url>
  <track_number>1</track_number>
  <duration_ms>148345</duration_ms>
  <artists>
    <artist>
      <id>2NpPlwwDVYR5dIj0F31EcC</id>
      <name>Leony</name>
    </artist>
  </artists>
  <album>
    <name>Faded Love</name>
    <release_date>2021-01-15</release_date>
    <release_date_precision>day</release_date_precision>
    <total_tracks>1</total_tracks>
    <artists>
      <artist>
        <id>2NpPlwwDVYR5dIj0F31EcC</id>
        <name>Leony</name>
      </artist>
    </artists>
    <image>
      <height>640</height>
      <width>640</width>
      <url>https://i.scdn.co/image/ab67616d0000b273f4345db90a9552a500b2fafc</url>
    </image>
  </album>
</track>
